import React, { useState } from 'react';
import { Sparkles, User, ChevronDown, ChevronUp, BookOpen } from 'lucide-react';
import { Message } from '../../types';

interface MessageBubbleProps {
  message: Message;
}

export const MessageBubble: React.FC<MessageBubbleProps> = ({ message }) => {
  const isUser = message.role === 'user';
  const [sourcesOpen, setSourcesOpen] = useState(false);

  return (
    <div className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'} mb-6`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] space-x-3 ${isUser ? 'flex-row-reverse space-x-reverse' : 'flex-row'}`}>
        {/* Avatar */}
        <div
          className={`w-8 h-8 rounded-full shrink-0 flex items-center justify-center text-xs font-semibold ${
            isUser
              ? 'bg-slate-800 text-white shadow-sm'
              : 'bg-brand-500 text-white shadow-sm shadow-brand-500/20'
          }`}
        >
          {isUser ? <User className="w-4 h-4" /> : <Sparkles className="w-4 h-4" />}
        </div>

        {/* Message Content Body */}
        <div className="flex flex-col space-y-2">
          <div
            className={`rounded-2xl px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap ${
              isUser
                ? 'bg-slate-900 text-white rounded-tr-sm shadow-sm'
                : 'bg-white border border-slate-200 text-slate-800 rounded-tl-sm shadow-sm'
            }`}
          >
            {message.content}
          </div>

          {/* Source Citations for Assistant Responses */}
          {!isUser && message.sources && message.sources.length > 0 && (
            <div className="bg-slate-50 border border-slate-200 rounded-xl p-3 text-xs">
              <button
                onClick={() => setSourcesOpen(!sourcesOpen)}
                className="flex items-center justify-between w-full text-slate-600 hover:text-slate-900 font-medium"
              >
                <div className="flex items-center space-x-1.5">
                  <BookOpen className="w-3.5 h-3.5 text-brand-500" />
                  <span>Referenced Knowledge Sources ({message.sources.length})</span>
                </div>
                {sourcesOpen ? (
                  <ChevronUp className="w-4 h-4" />
                ) : (
                  <ChevronDown className="w-4 h-4" />
                )}
              </button>

              {sourcesOpen && (
                <div className="mt-2.5 space-y-2 border-t border-slate-200/60 pt-2">
                  {message.sources.map((src, idx) => (
                    <div key={idx} className="bg-white p-2.5 rounded-lg border border-slate-100 space-y-1">
                      <div className="flex items-center justify-between text-[11px] font-semibold text-slate-700">
                        <span>{src.title || `Source #${idx + 1}`}</span>
                        {src.relevance_score !== undefined && (
                          <span className="text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded">
                            Score: {src.relevance_score}
                          </span>
                        )}
                      </div>
                      <p className="text-slate-500 text-[11px] line-clamp-3 leading-normal">
                        {src.content}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Model Tag */}
          {!isUser && message.model_used && (
            <span className="text-[10px] text-slate-400 self-start px-1">
              Generated by {message.model_used}
            </span>
          )}
        </div>
      </div>
    </div>
  );
};
